POST http://localhost:8000/api/documents
Content-Type: application/json

{
  "payload": {
    "type": "passport",
    "firstName": "Ivan",
    "lastName": "Ivanov",
    "citizenship": "Russia",
    "series": "XC",
    "number": "123456"
  }
}
